### ISSUE TITLE
我正在做的

### ISSUE THREAD

**Issue by Yann001** [930team/timeline#2]
1. 根据事件时间范围构建比例尺
2. 封装canvas绘制图形模块
3. 进行静态数据测试

**Comment by pea3nut** [comment]
关于模块的接口文档，如果你使用`jsdoc`风格的注释，可以使用`jsdoc`自动格式化成`markdown`源码，这样可以避免每次模块变动需要手动同步文档改动。

如果你要进行自动的格式化生成文档，请在`/bin`文件夹内建立文件/文件夹存放脚本文件，然后在`/bin/build.js`里面引用它。

例子可参考：
https://github.com/pea3nut/pea-event

**Comment by pea3nut** [comment]
一次请只完成一件事
